language: php

sudo: false

matrix:
    allow_failures:
        - php: nightly
    fast_finish: true
    include:
        - php: 5.4
          env: deps=low
        - php: 5.4
          env: WITH_CRYPTO=true
        - php: 5.5
        - php: 5.6
        - php: 7.0
          env: deps=low
        - php: 7.0
          env: WITH_CRYPTO=true
        - php: 7.1
        - php: hhvm
        - php: hhvm
          env: deps=low
        - php: nightly
     
before_script:
    - composer self-update
    - sh -c 'if [ "$WITH_CRYPTO" != "" ]; then pecl install crypto-0.2.2; fi;'
    - mkdir -p build/logs
    - if [[ $deps = low ]]; then composer update --no-interaction --prefer-lowest ; fi
    - if [[ !$deps ]]; then composer install --no-interaction ; fi

script:
    - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
    - php tests/Benchmark.php

after_success:
    - vendor/bin/coveralls --no-interaction
